/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function NFTMarketplace() {
  return (
    <main className="flex flex-col">
      <header className="justify-center items-center self-stretch bg-zinc-800 flex w-full flex-col mt-0 px-5 py-10 max-md:max-w-full">
        <div className="self-center w-full max-w-[1050px] -ml-5 my-10 max-md:max-w-full">
          <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
            <div className="flex flex-col items-stretch w-612 max-md:w-full">
              <div className="items-start flex grow flex-col max-md:max-w-full max-md:mt-8">
                <h1 className="items-start flex w-[510px] max-w-full flex-col text-white text-7xl font-semibold leading-[73.7px] capitalize self-stretch max-md:max-w-full max-md:text-4xl">
                  Discover digital art & Collect NFTs
                </h1>
                <p className="self-stretch text-white text-2xl leading-9 capitalize w-full mt-5 max-md:max-w-full">
                  NFT marketplace UI created with Anima for Figma. Collect, buy
                  and sell art from more than 20k NFT artists.
                </p>
              </div>
              <a
                href="#"
                className="justify-center items-center bg-purple-500 flex w-56 max-w-full flex-col mt-8 px-5 py-5 rounded-3xl"
              >
                <div className="self-center flex w-[124px] max-w-full items-start gap-3">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0eefda7a-9180-40de-99ed-e536df26a9eb?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0eefda7a-9180-40de-99ed-e536df26a9eb?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0eefda7a-9180-40de-99ed-e536df26a9eb?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0eefda7a-9180-40de-99ed-e536df26a9eb?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0eefda7a-9180-40de-99ed-e536df26a9eb?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0eefda7a-9180-40de-99ed-e536df26a9eb?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0eefda7a-9180-40de-99ed-e536df26a9eb?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0eefda7a-9180-40de-99ed-e536df26a9eb?apiKey=0a03bfded039464692f8a98b0a4cdb34&"
                    className="aspect-square object-cover object-center w-5 shrink-0 mt-px"
                  />
                  <div className="text-white text-center text-base font-semibold leading-6 self-stretch">
                    Get Started
                  </div>
                </div>
              </a>
              <div className="items-start flex w-[510px] max-w-full justify-between gap-5 mt-8 rounded-3xl max-md:flex-wrap max-md:justify-center">
                <div className="items-start self-stretch flex flex-col w-[150px] rounded-3xl">
                  <div className="self-stretch text-white text-3xl font-bold leading-10 capitalize w-full">
                    240k+
                  </div>
                  <div className="self-stretch text-white text-2xl leading-10 capitalize w-full">
                    Total Sale
                  </div>
                </div>
                <div className="items-start self-stretch flex flex-col w-[150px] rounded-3xl">
                  <div className="self-stretch text-white text-3xl font-bold leading-10 capitalize w-full">
                    100k+
                  </div>
                  <div className="self-stretch text-white text-2xl leading-10 capitalize w-full">
                    Auctions
                  </div>
                </div>
                <div className="items-start self-stretch flex flex-col w-[150px] rounded-3xl">
                  <div className="self-stretch text-white text-3xl font-bold leading-10 capitalize w-full">
                    240k+
                  </div>
                  <div className="self-stretch text-white text-2xl leading-10 capitalize w-full">
                    Artists
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full">
              <div className="items-center flex flex-col w-[510px] max-md:max-w-full max-md:mt-8">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/5d552948-082b-48b7-82b0-73a1427b3b5f?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d552948-082b-48b7-82b0-73a1427b3b5f?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d552948-082b-48b7-82b0-73a1427b3b5f?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d552948-082b-48b7-82b0-73a1427b3b5f?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d552948-082b-48b7-82b0-73a1427b3b5f?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d552948-082b-48b7-82b0-73a1427b3b5f?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d552948-082b-48b7-82b0-73a1427b3b5f?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/5d552948-082b-48b7-82b0-73a1427b3b5f?apiKey=0a03bfded039464692f8a98b0a4cdb34&"
                  className="aspect-[1.27] object-cover object-center w-full self-stretch rounded-3xl max-md:max-w-full"
                />
                <div className="justify-center items-center self-stretch bg-neutral-700 flex grow flex-col w-full px-5 py-6 rounded-none max-md:max-w-full">
                  <div className="self-stretch text-white text-2xl font-semibold leading-8 capitalize w-full">
                    Space Walking
                  </div>
                  <div className="items-start self-stretch flex justify-between gap-3 mt-2.5 rounded-3xl max-md:max-w-full max-md:flex-wrap">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0e8fd814-cb7f-42d6-94f0-89fcd4eea5be?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0e8fd814-cb7f-42d6-94f0-89fcd4eea5be?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0e8fd814-cb7f-42d6-94f0-89fcd4eea5be?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0e8fd814-cb7f-42d6-94f0-89fcd4eea5be?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0e8fd814-cb7f-42d6-94f0-89fcd4eea5be?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0e8fd814-cb7f-42d6-94f0-89fcd4eea5be?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0e8fd814-cb7f-42d6-94f0-89fcd4eea5be?apiKey=0a03bfded039464692f8a98b0a4cdb34&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0e8fd814-cb7f-42d6-94f0-89fcd4eea5be?apiKey=0a03bfded039464692f8a98b0a4cdb34&"
                      className="aspect-square object-cover object-center w-6 shrink-0"
                    />
                    <div className="text-white text-base leading-6 max-w-[467px] grow shrink-0 basis-auto max-md:max-w-full">
                      Animakid
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
    </main>
  );
}
